package config

// API endpoints group
const (
	// PingEndpoint ...
	PingEndpoint = "/api/ping"

	// UserRegisterEndpoint ...
	UserRegisterEndpoint = "/api/user/register"
	// UserLoginEndpoint ...
	UserLoginEndpoint = "/api/user/login"
	// UserProfileEndpoint ...
	UserProfileEndpoint = "/api/user/profile"
	// UserProfileUpdateEndpoint ...
	UserProfileUpdateEndpoint = "/api/user/profile/update"
	// UserLogoutEndpoint ...
	UserLogoutEndpoint = "/api/user/logout"

	// PaymentsListEndpoint ...
	PaymentsListEndpoint = "/api/payments/list"
	// PaymentsCreate ...
	PaymentsCreate = "/api/payments/create"
)
