package config

// API endpoints group
const (
	// PingEndpoint ...
	PingEndpoint = "/api/ping"

	// UserRegisterEndpoint ...
	UserRegisterEndpoint = "/user/register"
	// UserLoginEndpoint ...
	UserLoginEndpoint = "/user/login"
	// UserFetchProfileEndpoint ...
	UserFetchProfileEndpoint = "/user/profile/fetch"
	// UserProfileUpdateEndpoint ...
	UserProfileUpdateEndpoint = "/user/profile/update"
	// UserLogoutEndpoint ...
	UserLogoutEndpoint = "/user/logout"

	// PaymentsListEndpoint ...
	PaymentsListEndpoint = "/payments/list"
	// PaymentsCreate ...
	PaymentsCreate = "/payments/create"
	// PaymentsDelete ...
	PaymentsDelete = "/api/payments/delete"
)
